# https://docs.travis-ci.com/user/customizing-the-build

language: python
services:
  - docker

env:
  matrix:
    - name: "centos7"
      image: "centos:7"

install:
  - pip install ansible molecule[docker]

before_script:
  # Use the Ansible Galaxy role name
  - ln -s $PWD ../kirikae.install_foreman
  - cd ../kirikae.install_foreman

script:
  - molecule test

notifications:
  email:
    recipients:
      - devel@cs-network.org
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: always
    on_pull_requests: false