---
- name: "REGISTER | Register the system with Satellite / The Foreman (Activation Key)"
  redhat_subscription:
    state: present
    org_id: "{{ install_foreman_orgid }}"
    activationkey: "{{ install_foreman_activationkey }}"
  register: install_foreman_activation
  when: >
    (install_foreman_activationkey is defined)

- name: "REGISTER | Register the system with Satellite / The Foreman (User / Pass)"
  redhat_subscription:
    consumer_name: "{{ install_foreman_hostname_fqdn }}"
    username: "{{ install_foreman_rhn_username }}"
    password: "{{ install_foreman_rhn_password }}"
    state: present
  register: install_foreman_userpass
  when: >
    (install_foreman_rhn_username is defined) and
    (install_foreman_rhn_password is defined) and
    (install_foreman_activation is undefined)

- name: "REGISTER | Check for existing subscription"
  shell: >
    /usr/sbin/subscription-manager list
    --consumed
    --matches='Satellite*'
    | awk '/Pool ID/ {print $3}'
  register: install_foreman_satellite_subscription
  when: >
    (install_foreman_userpass is defined) and
    (install_foreman_activation is undefined)
  tags:
    - skip_ansible_lint  # ANSIBLE0012

- name: "REGISTER | Get RHN Satellite Pool ID"
  shell: >
    /usr/sbin/subscription-manager list
    --all
    --available
    --matches='Satellite*'
    | awk '/Pool ID/ {print $3}'
    | head -1
  register: install_foreman_satellite_pool_id_result
  changed_when: false
  when: >
    (install_foreman_satellite_pool_id is undefined) and
    (install_foreman_activation is undefined)
  tags:
    - skip_ansible_lint  # ANSIBLE0012

- name: "REGISTER | Set pool_id fact"
  set_fact:
    install_foreman_satellite_pool_id: "{{
      install_foreman_satellite_pool_id_result.stdout }}"
  when: >
    (install_foreman_satellite_pool_id is undefined) and
    (install_foreman_activation is undefined)

- name: "REGISTER | Subscribe to the Satellite Pool"
  redhat_subscription:
    username: "{{ install_foreman_rhn_username }}"
    password: "{{ install_foreman_rhn_password }}"
    pool_ids: "{{ install_foreman_satellite_pool_id }}"
    state: present
  when: >
    (install_foreman_satellite_pool_id is defined) and
    (install_foreman_activation is undefined)
