---
# tasks file for kirikae.install_foreman

- name: "MAIN | Include distribution / OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include_tasks: set_facts.yml
- include_tasks: prerequisites.yml
- include_tasks: register.yml
  when: >
    (install_foreman_satellite |bool) and
    (install_foreman_is_connected |bool)
- include_tasks: repositories.yml
  when: >
    not(install_foreman_satellite |bool)
- include_tasks: firewall.yml
- include_tasks: packages.yml
- include_tasks: application.yml
