---
- name: "PRE-REQUISITES | Install Ansible required packages"
  package:
    name: "{{ install_foreman_ansible_packages }}"
    state: present

- name: "PRE-REQUISITES | Set hostname to FQDN"
  hostname:
    name: "{{ install_foreman_hostname_fqdn }}"

- name: "PRE-REQUISITES | Update /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ ansible_default_ipv4['address'] }}.*{{ install_foreman_hostname_fqdn }} {{ install_foreman_hostname_fqdn.split('.')[0] }}"
    line: "{{ ansible_default_ipv4['address'] }}{{ '\t' }}{{ install_foreman_hostname_fqdn }} {{ install_foreman_hostname_fqdn.split('.')[0] }}"
