---
- name: "REPOSITORIES | Include distribution specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: "REPOSITORIES | Include repository configuration (connected)"
  include_tasks: connected.yml
  when: install_foreman_is_connected |bool

- name: "REPOSITORIES | Include repository configuration (disconnected)"
  include_tasks: disconnected.yml
  when: not(install_foreman_is_connected |bool)

#- name: "REPOSITORIES | "
