---

- name: "REPOSITORIES | Include repository configuration (connected)"
  include_tasks: connected.yml
  when: install_foreman_is_connected |bool

- name: "REPOSITORIES | Include repository configuration (disconnected)"
  include_tasks: disconnected.yml
  when: not(install_foreman_is_connected |bool)
