---
- name: "FACTS | Set remote_manifest fact"
  set_fact:
    install_foreman_remote_manifest: "{{
      'http://' in install_foreman_manifest_path or
      'ftp://' in install_foreman_manifest_path }}"
  when: install_foreman_manifest | bool

- name: "FACTS | Ensure /etc/ansible/facts.d exists"
  file:
    path: /etc/ansible/facts.d
    state: directory
    recurse: true
    owner: root
    group: root

- name: "FACTS | Create the install_foreman local_facts"
  template:
    src: install_foreman.fact.j2
    dest: /etc/ansible/facts.d/install_foreman.fact
    owner: root
    group: root
  register: local_fact_result

- name: "FACTS | Re-Gather facts"
  setup:
  when: local_fact_result is changed
