---
- name: "FACTS | Set remote_manifest fact"
  set_fact:
    install_foreman_remote_manifest: "{{
      'http://' in install_foreman_manifest_path or
      'ftp://' in install_foreman_manifest_path }}"
  when: install_foreman_manifest | bool
