---
scenario:
  name: vagrant-test
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    # - destroy

lint:
  name: yamllint

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: centos7.example.com
    box: centos/7
    raw_config_args:
      - "cpu_mode = 'host-passthrough'"
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "ssh.insert_key = false"
    memory: 8192
    cpus: 4
    groups:
      - foreman

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - ../../roles/linux-system-roles.timesync
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
  options:
    e: "@ansible-override-vars.yml"
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
