---
scenario:
  name: vagrant-test
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

lint:
  name: yamllint

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: foreman.example.com
    box: centos/7
    raw_config_args:
      - "cpu_mode = 'host-passthrough'"
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
      - "ssh.insert_key = false"
      # - "vm.network 'private_network', ip: '192.168.144.222'"
    memory: 4096
    private_ip: 192.168.144.222
    cpus: 2
    groups:
      - foreman

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    e: "@ansible-override-vars.yml"
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
